# Generated by Django 5.1.6 on 2025-02-28 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='fechaCompra',
        ),
    ]
