# Generated by Django 5.1.6 on 2025-05-21 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_categoria_options_alter_cliente_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiado',
            name='CuentaCliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.cuentacliente'),
            preserve_default=False,
        ),
    ]
