# Generated by Django 5.1.6 on 2025-05-29 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_fiado_cuentacliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='cantidad',
        ),
    ]
