# Generated by Django 5.1.6 on 2025-05-29 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_producto_cantidad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fiado',
            old_name='fechaPago',
            new_name='fechaUltimoPago',
        ),
    ]
