# Generated by Django 5.1.6 on 2025-05-30 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_fechapago_fiado_fechaultimopago'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EstadoPedido',
        ),
        migrations.AddField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('enviado', 'Enviado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=50),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='estadoProducto',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=50),
        ),
    ]
