# Generated by Django 5.1.6 on 2025-05-31 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_delete_estadopedido_pedido_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentacliente',
            name='montoTotal',
            field=models.FloatField(default=0.0),
        ),
    ]
