# Generated by Django 5.1.6 on 2025-05-31 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_cuentacliente_montototal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fiado',
            old_name='CuentaCliente',
            new_name='cuentaCliente',
        ),
    ]
