# Generated by Django 5.1.6 on 2025-06-02 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_cuentacliente_fiado_cuentacliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallepedido',
            name='fechaIngreso',
        ),
        migrations.RemoveField(
            model_name='detallepedido',
            name='marcas',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='cliente',
        ),
        migrations.AddField(
            model_name='pedido',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.proveedor'),
        ),
    ]
