# Generated by Django 5.1.6 on 2025-06-02 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_detallepedido_fechaingreso_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='calificacion',
        ),
        migrations.AddField(
            model_name='proveedor',
            name='comentarios',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
