# Generated by Django 5.1.6 on 2025-06-03 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_lote'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='dias_alerta_vencimiento',
            field=models.IntegerField(default=15),
        ),
    ]
