# Generated by Django 5.1.6 on 2025-06-04 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_categoria_dias_alerta_vencimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='acceso_clientes',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='acceso_compras',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='acceso_cuentas',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='acceso_inventario',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='acceso_productos',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='acceso_proveedores',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='acceso_ventas',
            field=models.BooleanField(default=True),
        ),
    ]
