# Generated by Django 5.1.6 on 2025-06-05 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_usuario_acceso_clientes_usuario_acceso_compras_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
